apiVersion: apps/v1
kind: Deployment
metadata:
  name: logs_inject_tool-deployment
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: logs_inject_tool
        image: nginx:1.7.9